name: Deploy Inventory App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/inventory.zioan.com
            if [ ! -d ".git" ]; then
              git clone https://github.com/zioan/pp3_inventory.git .
            else
              git pull origin main
            fi
            source venv/bin/activate
            pip install -r requirements.txt
            npm install
            sudo systemctl restart inventory
